#!/usr/bin/env bash
# Function to display information about a subdomain
display_info() {
    domain=$1
    subdomain=$2

    # Define IP addresses based on the provided information
    case $subdomain in
        "www") destination="35.153.51.85" ;;
        "lb-01") destination="35.153.51.85" ;;
        "web-01") destination="100.25.167.92" ;;
        "web-02") destination="18.234.168.83" ;;
        *) destination="" ;;
    esac

    # Display the information
    if [ -n "$destination" ]; then
        echo "The subdomain ${subdomain} is a A record and points to ${destination}"
    else
        echo "Invalid subdomain: ${subdomain}"
    fi
}

# Main script
domain="mefualx.tech"

display_info "$domain" "www"
display_info "$domain" "lb-01"
display_info "$domain" "223498-web-01"
display_info "$domain" "223498-web-02"
