#!/usr/bin/env bash
# Bash script containing commands to automatically
# configure a Ubuntu machine

server {
    # Other server configurations...

    location / {
        default_type text/plain;
        echo "Hello World!\n";
    }

    # Redirect 1: Redirect /redirect1 to https://example.com
    location /redirect1 {
        return 301 https://example.com;
    }

    # Redirect 2: Redirect /redirect2 to http://example.tech
    location /redirect2 {
        return 301 http://example.tech;
    }

    # Redirect 3: Redirect /redirect3 to a different path /newpath
    location /redirect3 {
        return 301 /newpath;
    }

    # Additional configurations...
}
