#!/usr/bin/env bash
# Update packages
sudo apt-get update
sudo apt update -y

# Install HAProxy
sudo apt install haproxy -y

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<'EOF'
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend  mefualx-frontend
        bind *:80
        mode http
        default_backend mefualx-backend
backend mefualx-backend
        balance roundrobin
        server 223498-web-01 100.25.167.92:80 check
        server 223498-web-02 18.234.168.83:80 check
EOF

# Enable HAProxy as a service
sudo systemctl enable haproxy

# Restart HAProxy to apply changes
sudo systemctl restart haproxy
