#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# a custom header
#
balancer="\
defaults
    mode http
    balance roundrobin
    option forwardfor
    option http-server-close

frontend haproxy_balancer
    bind *:80
    default_backend webservers

backend webservers
    balance roundrobin
    server 223498-web-01 100.25.167.92:80 check
    server 223498-web-02 18.234.168.83:80 check
"
# Update packages
apt-get -y update
apt-get -y upgrade

# Add HAProxy PPA

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update

# Install HAProxy
apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" > /etc/haproxy/haproxy.cfg
service haproxy restart
