#!/usr/bin/env bash
# configures a server to listening on port 80 of all server's active IPv4 IPs

sudo apt-get update
sudo apt-get install -y net-tools nginx

# Check if Nginx is running and listening on port 80
if ! netstat -tulpn | grep -q ':80'; then
    # Edit the default Nginx configuration
    sudo sed -i '/listen 80;/! s/server {/server {\n    listen 80;/g' /etc/nginx/sites-available/default

    # Test Nginx configuration for syntax errors
    if sudo nginx -t; then
        # Restart Nginx if the configuration is valid
        sudo service nginx restart
        echo "Nginx configured to listen on port 80."
    else
        echo "Nginx configuration test failed. Please check your configuration."
    fi
else
    echo "Nginx is already listening on port 80."
fi

# sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
# sudo service nginx restart
