#!/usr/bin/env bash

# Set the file path for the private key
private_key_path="school"

# Number of bits for the RSA key
key_bits=4096

# Passphrase for the key
passphrase="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b "$key_bits" -f "$private_key_path" -N "$passphrase"
